name: Firebase Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` cmd
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn install` cmd
      - uses: w9jds/firebase-action@master # looking for FIREBASE_TOKEN
        with:
          args: deploy --only hosting